name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: akimanabe/latex-action@master
        with:
          working_directory: ./
          root_file: tex_practice.tex
          args: ""
      - name: Upload pdf
        uses: actions/upload-artifact@v1
        with:
          name: Download
          path: tex_practice.pdf
